import { useEffect, useRef, useState } from "react";
import { Html5QrcodeScanner, Html5QrcodeScanType } from "html5-qrcode";
import {
  Camera, User, Mail, Phone, Building2, Briefcase, Calendar,
  RefreshCw, QrCode, CheckCircle, XCircle, ExternalLink
} from "lucide-react";
import axios from "axios";
import toast from "react-hot-toast";
import { extractEmpId } from "../utils/qrUrl";

// Use the same LAN-aware API base as the rest of the app
const API = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

/**
 * QR Scanner Page
 * Uses html5-qrcode to scan employee QR codes via camera or file upload.
 * Fetches employee details from the backend using the scanned empId.
 * This route is PUBLIC — no auth required to look up employees.
 */
export default function QRScanner() {
  const scannerRef = useRef(null);
  const [scanning, setScanning]   = useState(false);
  const [employee, setEmployee]   = useState(null);
  const [error, setError]         = useState(null);
  const [loading, setLoading]     = useState(false);

  // Start scanner on mount
  useEffect(() => {
    initScanner();
    return () => {
      // Clean up scanner on unmount
      if (scannerRef.current) {
        scannerRef.current.clear().catch(() => {});
      }
    };
  }, []);

  const initScanner = () => {
    setEmployee(null);
    setError(null);

    const scanner = new Html5QrcodeScanner(
      "qr-reader",
      {
        fps: 10,
        qrbox: { width: 240, height: 240 },
        supportedScanTypes: [
          Html5QrcodeScanType.SCAN_TYPE_CAMERA,
          Html5QrcodeScanType.SCAN_TYPE_FILE,
        ],
        rememberLastUsedCamera: true,
      },
      /* verbose= */ false
    );

    scanner.render(onScanSuccess, onScanError);
    scannerRef.current = scanner;
    setScanning(true);
  };

  const onScanSuccess = async (decodedText) => {
    // Stop scanner after successful scan
    if (scannerRef.current) {
      await scannerRef.current.clear().catch(() => {});
    }
    setScanning(false);

    /*
     * QR codes generated by this app after the upgrade embed a full URL:
     *   http://localhost:5173/employee/EMP-001
     * Older printed cards may have stored just the raw empId: "EMP-001"
     * extractEmpId() handles both cases transparently.
     */
    const empId = extractEmpId(decodedText);
    await fetchEmployee(empId);
  };

  const onScanError = () => {
    // Suppress frame-by-frame errors (these are normal)
  };

  const fetchEmployee = async (empId) => {
    setLoading(true);
    setError(null);
    try {
      const { data } = await axios.get(`${API}/employees/${encodeURIComponent(empId)}`);
      setEmployee(data);
      toast.success("Employee found!");
    } catch (err) {
      const msg = err.response?.data?.message || "Employee not found";
      setError(msg);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  const handleRescan = () => {
    setEmployee(null);
    setError(null);
    initScanner();
  };

  return (
    <div className="page-wrapper p-6 max-w-xl mx-auto space-y-5">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">QR Scanner</h2>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          Scan an employee QR code to fetch their profile.
        </p>
      </div>

      {/* Scanner */}
      {!employee && !error && (
        <div className="card p-4">
          <div className="flex items-center gap-2 mb-4 text-gray-600 dark:text-gray-400 text-sm">
            <Camera className="w-4 h-4 text-primary-500" />
            <span>Position the QR code inside the frame</span>
          </div>
          <div id="qr-reader" className="w-full" />
          {loading && (
            <div className="flex items-center justify-center gap-2 mt-4 text-primary-500">
              <RefreshCw className="w-4 h-4 animate-spin" />
              <span className="text-sm">Fetching employee details…</span>
            </div>
          )}
        </div>
      )}

      {/* Error state */}
      {error && (
        <div className="card text-center space-y-4 animate-fade-in">
          <div className="w-14 h-14 bg-red-100 dark:bg-red-900/30 rounded-2xl flex items-center justify-center mx-auto">
            <XCircle className="w-7 h-7 text-red-500" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-gray-900 dark:text-white">Not Found</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{error}</p>
          </div>
          <button id="rescan-btn" onClick={handleRescan} className="btn-primary mx-auto">
            <QrCode className="w-4 h-4" /> Scan Again
          </button>
        </div>
      )}

      {/* Employee profile card */}
      {employee && (
        <div className="card animate-fade-in space-y-5">
          {/* Header */}
          <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 text-sm font-medium">
            <CheckCircle className="w-4 h-4" />
            Employee identified
          </div>

          {/* Profile */}
          <div className="flex items-center gap-4">
            {employee.photo ? (
              <img src={employee.photo} alt={employee.name}
                className="w-16 h-16 rounded-2xl object-cover flex-shrink-0" />
            ) : (
              <div className="w-16 h-16 rounded-2xl bg-primary-100 dark:bg-primary-900/30 flex items-center justify-center flex-shrink-0">
                <span className="text-primary-700 dark:text-primary-400 font-bold text-2xl">
                  {employee.name.charAt(0)}
                </span>
              </div>
            )}
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">{employee.name}</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">{employee.designation}</p>
              <span className="badge-purple mt-1">{employee.department}</span>
            </div>
          </div>

          {/* Details grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { icon: User,      label: "Employee ID",  value: employee.empId },
              { icon: Mail,      label: "Email",        value: employee.email },
              { icon: Phone,     label: "Phone",        value: employee.phone },
              { icon: Building2, label: "Department",   value: employee.department },
              { icon: Briefcase, label: "Designation",  value: employee.designation },
              {
                icon: Calendar,
                label: "Joined",
                value: new Date(employee.joiningDate).toLocaleDateString("en-IN", {
                  day: "numeric", month: "long", year: "numeric"
                }),
              },
            ].map(({ icon: Icon, label, value }) => (
              <div key={label} className="flex items-start gap-3 p-3 rounded-xl bg-gray-50 dark:bg-gray-700/50">
                <div className="w-7 h-7 bg-primary-100 dark:bg-primary-900/30 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                  <Icon className="w-3.5 h-3.5 text-primary-600 dark:text-primary-400" />
                </div>
                <div>
                  <p className="text-xs text-gray-400 font-medium">{label}</p>
                  <p className="text-sm text-gray-800 dark:text-white font-medium break-all">{value}</p>
                </div>
              </div>
            ))}
          </div>

          <button id="scan-again-btn" onClick={handleRescan} className="btn-secondary w-full justify-center">
            <QrCode className="w-4 h-4" /> Scan Another QR
          </button>
          <a
            href={`/employee/${employee.empId}`}
            target="_blank"
            rel="noreferrer"
            className="flex items-center justify-center gap-1.5 text-sm text-primary-500 hover:underline pt-1"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            Open Full Profile Page
          </a>
        </div>
      )}
    </div>
  );
}
